---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ironic-pv-volume
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: {{ .Values.ironic.ironic_storage.volume_capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.ironic.ironic_storage.hostPath }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ironic-pv-claim
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ironic.ironic_storage.volume_capacity }}
