---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metal3-baremetal-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: metal3-baremetal-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - metal3.io
  resources:
  - '*'
  verbs:
  - '*'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metal3-baremetal-operator
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: metal3-baremetal-operator
- kind: User
  name: developer
roleRef:
  kind: Role
  name: metal3-baremetal-operator
  apiGroup: rbac.authorization.k8s.io
