{{- if eq .Values.version "v1alpha2" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capbm-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capbm-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
{{- end }}
