apiVersion: apps/v1
kind: Deployment
metadata:
  name: metal3-baremetal-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metal3-baremetal-operator
  template:
    metadata:
      labels:
        name: metal3-baremetal-operator
    spec:
      serviceAccountName: metal3-baremetal-operator
      containers:
        - name: baremetal-operator
          image: {{ .Values.operator.image }}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - /baremetal-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "baremetal-operator"
            - name: DEPLOY_KERNEL_URL
              value: "{{ .Values.operator.deploy_kernel_url }}"
            - name: DEPLOY_RAMDISK_URL
              value: "{{ .Values.operator.deploy_ramdisk_url }}"
            - name: IRONIC_ENDPOINT
              value: {{ .Values.operator.ironic_api_url }}
            - name: IRONIC_INSPECTOR_ENDPOINT
              value: "{{ .Values.operator.ironic_inspector_url }}"

